; Minimal text renderer: an 8x8 monospace font (ASCII $20 "space" through
; $5F "_" -- uppercase, digits, basic punctuation -- plus $60 "`" through
; $7A "z" -- lowercase -- tile index = ascii-$20) and a couple of
; primitives to load it and print null-terminated ROM strings into the
; BG tilemap. No word-wrap, no scrolling -- exactly enough for short,
; fixed-position diagnostic status lines.
;
; The font bitmap data below is a straightforward 1-bit-per-pixel
; rasterization of a standard system monospace typeface at 8x8,
; thresholded to solid on/off pixels, generated by a local script for
; this project -- not a copied/embedded font file, and not derived from
; any Nintendo/Pokemon asset (see the repo-root CLAUDE.md's Copyright /
; Clean-Room Considerations section). The lowercase tiles ($60-$7A)
; were added later than the rest -- until then this font had no
; lowercase at all, which became a real, visible gap once the config
; screen (login id/email/SMTP/POP fields) and the ISP PASSWORD editor
; started needing to actually show/type realistic values (see
; docs/status.md). Lowercase glyphs use the same 5-column-wide cell
; (bits 7-3 of each row byte; bits 2-0 always 0) as the uppercase set,
; sized to the same 8-row tile -- x-height letters occupy rows 2-6,
; ascenders (b,d,f,h,k,l,t) extend into rows 0-1, descenders
; (g,j,p,q,y) extend into row 7.

INCLUDE "hardware.inc"

SECTION "Text Code", ROM0

; Copies the 64-tile font into VRAM tile block 0 ($8000-$83FF). Turns
; the LCD off for the duration itself (same approach as PrintString/
; ClearTextScreen below) -- VRAM isn't safely writable with the LCD on
; outside HBlank/VBlank, and this copies more than fits reliably in
; either window. An earlier version relied on the caller (main.asm's
; InitDisplayBlank) leaving the LCD off, but InitDisplayBlank turns it
; back on before returning, so most of this copy raced the PPU and had
; its writes silently dropped mid-transfer -- confirmed by seeing
; partial/broken-looking glyphs in BGB (correct tile *numbers*, corrupt
; tile *data*) instead of a hang or a blank screen.
;
; Waits for VBlank before turning the LCD off, same reason as
; PrintString below -- turning LCDC off is itself only well-defined at
; the start of VBlank; doing it from an arbitrary point mid-scanline is
; the same class of hazard as writing VRAM with the LCD on, just on the
; control register instead of the data.
; Clobbers: A, BC, HL, DE
LoadFont::
    call WaitVBlank
    xor a, a
    ldh [rLCDC], a

    ld hl, FontTiles
    ld de, $8000
    ld bc, FontTilesEnd - FontTiles
.loop
    ld a, [hl+]
    ld [de], a
    inc de
    dec bc
    ld a, b
    or a, c
    jr nz, .loop

    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BG_TILEDATA
    ldh [rLCDC], a
    ret

; Prints a null-terminated ASCII string (chars $20-$5F only) into the BG
; tilemap starting at a given address. Turns the LCD off for the
; duration (simplest way to make this safe to call from anywhere,
; regardless of how long the string is or what PPU mode happens to be
; active at the time -- diagnostic code, not a hot path) and back on
; when done.
;
; Waits for VBlank first -- confirmed the hard way via the menu screen
; (main.asm's DrawMenu), which calls this back-to-back ~14 times with no
; delay between calls to redraw every item: without waiting here,
; enough of those calls landed mid-scanline (LCD turned off outside
; VBlank, undefined on real hardware) that the PPU's internal state got
; thrown off badly enough to render a blank white screen for several
; frames afterward -- not a hang (LCDC read back on afterward, VRAM
; contents were even still correct), just a PPU timing hazard invisible
; when this was only ever called a few, naturally-spaced-out times per
; screen (every previous milestone's actual call pattern).
;
; Input:  HL = string pointer (ROM), DE = tilemap destination address
;         (e.g. $9800 + row*32 + col)
; Clobbers: A, HL, DE
PrintString::
    call WaitVBlank ; clobbers only A -- HL/DE (this call's own inputs) survive
    xor a, a
    ldh [rLCDC], a
.loop
    ld a, [hl+]
    or a, a
    jr z, .done
    sub a, $20 ; ascii -> tile index
    ld [de], a
    inc de
    jr .loop
.done
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BG_TILEDATA
    ldh [rLCDC], a
    ret

; Fills the entire 32x32 BG tilemap with tile 0 (space, blank). Same
; LCD-off/on safety approach as PrintString.
;
; The zero-check runs *before* each write (see main.asm's FillMemory
; comment for why): an earlier version checked after writing and reused
; A for both "the value being written" and "BC==0 scratch", so only the
; very first tile actually got cleared and the rest of the screen kept
; whatever pattern was already in VRAM.
; Clobbers: A, BC, HL
ClearTextScreen::
    call WaitVBlank ; see PrintString's comment for why
    xor a, a
    ldh [rLCDC], a

    ld hl, $9800
    ld bc, 32 * 32
.loop
    ld a, b
    or a, c
    jr z, .cleared
    xor a, a
    ld [hl+], a
    dec bc
    jr .loop

.cleared
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BG_TILEDATA
    ldh [rLCDC], a
    ret

; Prints A as two uppercase hex digits (no "$"/"0x" prefix) at a tilemap
; address -- the RGBDS-side equivalent of gbdk's printf("%hx", byte),
; used for showing a captured adapter device id. Builds real ASCII
; bytes ('0'-'9','A'-'F') into a scratch buffer first and hands that to
; PrintString, rather than poking tile indices directly, so this stays
; just as binary-safe/reusable as every other PrintString caller.
;
; Input: A = byte value, DE = tilemap destination address
; Clobbers: A, BC, HL, DE
PrintHexByte::
    ld c, a
    swap a
    and a, $0F
    call .nibbleToAscii
    ld [wHexScratch], a

    ld a, c
    and a, $0F
    call .nibbleToAscii
    ld [wHexScratch + 1], a

    xor a, a
    ld [wHexScratch + 2], a

    ld hl, wHexScratch
    jp PrintString

.nibbleToAscii
    cp a, 10
    jr c, .digit
    add a, "A" - 10
    ret
.digit
    add a, "0"
    ret

; Prints `len` raw bytes at [HL] into the tilemap at DE, replacing any
; byte outside this font's printable range ($20-$7A) with '.' -- these
; are fixed-length raw config fields (login ID, email, ...), not
; necessarily NUL-terminated or even printable (an unconfigured field
; is commonly all $00 or $FF). The RGBDS-side equivalent of gbdk's
; print_ascii_field(), just with a slightly narrower "printable" range
; matching this font's actual coverage ($20-$7A, not gbdk's $20-$7E --
; this font has no punctuation/symbols past 'z').
;
; Input: HL = source bytes, B = length, DE = tilemap destination
; Clobbers: everything
PrintAsciiField::
    call WaitVBlank
    xor a, a
    ldh [rLCDC], a
.loop
    ld a, b
    or a, a
    jr z, .done
    ld a, [hl+]
    cp a, $20
    jr c, .dot
    cp a, $7B ; one past 'z' ($7A) -- this font's last tile
    jr nc, .dot
    sub a, $20
    jr .store
.dot
    ld a, "." - $20
.store
    ld [de], a
    inc de
    dec b
    jr .loop
.done
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BG_TILEDATA
    ldh [rLCDC], a
    ret

; Prints 4 bytes as a dotted-decimal quad (e.g. an IPv4 address),
; "N.N.N.N", no leading zeros per octet -- the RGBDS-side equivalent of
; gbdk's printf("%u.%u.%u.%u", ...).
;
; Input: HL = 4-byte source, DE = tilemap destination address
; Clobbers: everything
PrintDottedQuad::
    push de
    ld de, wQuadScratch
    ld b, 0
.octetLoop
    ld a, [hl+]
    push bc
    call BuildDecimal ; clobbers A/BC only, advances DE -- HL/B(our own) survive
    pop bc

    ld a, b
    cp a, 3
    jr z, .noDot
    ld a, "."
    ld [de], a
    inc de
.noDot
    inc b
    ld a, b
    cp a, 4
    jr nz, .octetLoop

    xor a, a
    ld [de], a

    pop de
    ld hl, wQuadScratch
    jp PrintString

; Appends A (0-255) as decimal ASCII digits (no leading zeros) at [DE],
; advancing DE past what it wrote -- PrintDottedQuad's own digit
; primitive; nothing else in this ROM needs decimal (byte counts/status
; codes elsewhere are always shown in hex via PrintHexByte, matching
; gbdk's printf("%hx", ...) convention there).
;
; Input: A = value, DE = dest ptr (advanced on return)
; Clobbers: A, BC
BuildDecimal::
    ld [wDecValue], a
    xor a, a
    ld [wDecStarted], a

    ld c, 100
    call .place
    ld c, 10
    call .place

    ld a, [wDecValue]
    add a, "0"
    ld [de], a
    inc de
    ret

; Input: C = place value (100 or 10)
.place
    xor a, a
    ld [wDecDigit], a
.divLoop
    ld a, [wDecValue]
    cp a, c
    jr c, .divDone
    sub a, c
    ld [wDecValue], a
    ld a, [wDecDigit]
    inc a
    ld [wDecDigit], a
    jr .divLoop
.divDone
    ld a, [wDecDigit]
    or a, a
    jr nz, .print
    ld a, [wDecStarted]
    or a, a
    ret z ; still 0 and not started yet: suppress the leading zero
.print
    ld a, 1
    ld [wDecStarted], a
    ld a, [wDecDigit]
    add a, "0"
    ld [de], a
    inc de
    ret

SECTION "Text Scratch", WRAM0
wHexScratch: ds 3 ; 2 hex digits + null, for PrintHexByte
wQuadScratch: ds 16 ; "255.255.255.255" + null, for PrintDottedQuad
wDecValue: db  ; BuildDecimal's remaining value
wDecDigit: db  ; BuildDecimal's current digit
wDecStarted: db ; BuildDecimal: 0 = still suppressing leading zeros

SECTION "Text Code 2", ROM0

FontTiles:
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;   0 'space'
    db $00,$00,$20,$00,$20,$00,$20,$00,$20,$00,$00,$00,$20,$00,$00,$00 ;   1 '!'
    db $00,$00,$50,$00,$50,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;   2 '"'
    db $00,$00,$00,$00,$30,$00,$F8,$00,$50,$00,$F0,$00,$20,$00,$00,$00 ;   3 '#'
    db $00,$00,$20,$00,$70,$00,$60,$00,$70,$00,$30,$00,$70,$00,$20,$00 ;   4 '$'
    db $00,$00,$40,$00,$A0,$00,$70,$00,$70,$00,$28,$00,$10,$00,$00,$00 ;   5 '%'
    db $00,$00,$70,$00,$40,$00,$60,$00,$A8,$00,$90,$00,$78,$00,$00,$00 ;   6 '&'
    db $00,$00,$20,$00,$20,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;   7 '''
    db $20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;   8 '('
    db $40,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$40,$00,$00,$00 ;   9 ')'
    db $00,$00,$20,$00,$70,$00,$70,$00,$20,$00,$00,$00,$00,$00,$00,$00 ;  10 '*'
    db $00,$00,$00,$00,$20,$00,$20,$00,$F8,$00,$20,$00,$20,$00,$00,$00 ;  11 '+'
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$20,$00,$20,$00 ;  12 ','
    db $00,$00,$00,$00,$00,$00,$00,$00,$70,$00,$00,$00,$00,$00,$00,$00 ;  13 '-'
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$20,$00,$00,$00 ;  14 '.'
    db $00,$00,$10,$00,$10,$00,$20,$00,$20,$00,$00,$00,$40,$00,$40,$00 ;  15 '/'
    db $00,$00,$70,$00,$50,$00,$70,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  16 '0'
    db $00,$00,$60,$00,$20,$00,$20,$00,$20,$00,$20,$00,$70,$00,$00,$00 ;  17 '1'
    db $00,$00,$70,$00,$10,$00,$10,$00,$20,$00,$40,$00,$F0,$00,$00,$00 ;  18 '2'
    db $00,$00,$70,$00,$10,$00,$30,$00,$10,$00,$10,$00,$F0,$00,$00,$00 ;  19 '3'
    db $00,$00,$30,$00,$30,$00,$50,$00,$50,$00,$F0,$00,$10,$00,$00,$00 ;  20 '4'
    db $00,$00,$70,$00,$40,$00,$70,$00,$10,$00,$10,$00,$70,$00,$00,$00 ;  21 '5'
    db $00,$00,$70,$00,$40,$00,$70,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  22 '6'
    db $00,$00,$70,$00,$10,$00,$30,$00,$20,$00,$20,$00,$40,$00,$00,$00 ;  23 '7'
    db $00,$00,$70,$00,$50,$00,$70,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  24 '8'
    db $00,$00,$70,$00,$50,$00,$D0,$00,$70,$00,$10,$00,$60,$00,$00,$00 ;  25 '9'
    db $00,$00,$00,$00,$00,$00,$20,$00,$00,$00,$00,$00,$20,$00,$00,$00 ;  26 ':'
    db $00,$00,$00,$00,$00,$00,$20,$00,$00,$00,$00,$00,$20,$00,$20,$00 ;  27 ';'
    db $00,$00,$00,$00,$10,$00,$60,$00,$60,$00,$10,$00,$00,$00,$00,$00 ;  28 '<'
    db $00,$00,$00,$00,$00,$00,$F0,$00,$00,$00,$F0,$00,$00,$00,$00,$00 ;  29 '='
    db $00,$00,$00,$00,$C0,$00,$30,$00,$30,$00,$C0,$00,$00,$00,$00,$00 ;  30 '>'
    db $00,$00,$70,$00,$10,$00,$30,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;  31 '?'
    db $00,$00,$00,$00,$70,$00,$D0,$00,$B8,$00,$A8,$00,$B8,$00,$40,$00 ;  32 '@'
    db $00,$00,$20,$00,$70,$00,$50,$00,$50,$00,$70,$00,$98,$00,$00,$00 ;  33 'A'
    db $00,$00,$F0,$00,$D0,$00,$D0,$00,$F0,$00,$D0,$00,$F0,$00,$00,$00 ;  34 'B'
    db $00,$00,$30,$00,$40,$00,$40,$00,$40,$00,$40,$00,$30,$00,$00,$00 ;  35 'C'
    db $00,$00,$60,$00,$50,$00,$50,$00,$50,$00,$50,$00,$60,$00,$00,$00 ;  36 'D'
    db $00,$00,$70,$00,$40,$00,$40,$00,$70,$00,$40,$00,$70,$00,$00,$00 ;  37 'E'
    db $00,$00,$70,$00,$40,$00,$40,$00,$70,$00,$40,$00,$40,$00,$00,$00 ;  38 'F'
    db $00,$00,$70,$00,$40,$00,$40,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  39 'G'
    db $00,$00,$50,$00,$50,$00,$50,$00,$70,$00,$50,$00,$50,$00,$00,$00 ;  40 'H'
    db $00,$00,$70,$00,$20,$00,$20,$00,$20,$00,$20,$00,$70,$00,$00,$00 ;  41 'I'
    db $00,$00,$70,$00,$10,$00,$10,$00,$10,$00,$10,$00,$F0,$00,$00,$00 ;  42 'J'
    db $00,$00,$D0,$00,$F0,$00,$E0,$00,$E0,$00,$D0,$00,$D8,$00,$00,$00 ;  43 'K'
    db $00,$00,$40,$00,$40,$00,$40,$00,$40,$00,$40,$00,$78,$00,$00,$00 ;  44 'L'
    db $00,$00,$D0,$00,$D0,$00,$F0,$00,$B0,$00,$90,$00,$90,$00,$00,$00 ;  45 'M'
    db $00,$00,$D0,$00,$D0,$00,$F0,$00,$B0,$00,$90,$00,$90,$00,$00,$00 ;  46 'N'
    db $00,$00,$70,$00,$50,$00,$D0,$00,$D0,$00,$50,$00,$70,$00,$00,$00 ;  47 'O'
    db $00,$00,$70,$00,$50,$00,$50,$00,$70,$00,$40,$00,$40,$00,$00,$00 ;  48 'P'
    db $00,$00,$70,$00,$50,$00,$D0,$00,$D0,$00,$50,$00,$70,$00,$10,$00 ;  49 'Q'
    db $00,$00,$70,$00,$50,$00,$50,$00,$70,$00,$50,$00,$58,$00,$00,$00 ;  50 'R'
    db $00,$00,$70,$00,$40,$00,$60,$00,$30,$00,$10,$00,$70,$00,$00,$00 ;  51 'S'
    db $00,$00,$F0,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;  52 'T'
    db $00,$00,$D0,$00,$D0,$00,$D0,$00,$D0,$00,$50,$00,$70,$00,$00,$00 ;  53 'U'
    db $00,$00,$90,$00,$50,$00,$50,$00,$50,$00,$70,$00,$60,$00,$00,$00 ;  54 'V'
    db $00,$00,$88,$00,$88,$00,$A8,$00,$F0,$00,$50,$00,$50,$00,$00,$00 ;  55 'W'
    db $00,$00,$D0,$00,$70,$00,$20,$00,$20,$00,$50,$00,$D0,$00,$00,$00 ;  56 'X'
    db $00,$00,$D8,$00,$50,$00,$70,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;  57 'Y'
    db $00,$00,$70,$00,$10,$00,$20,$00,$60,$00,$40,$00,$F8,$00,$00,$00 ;  58 'Z'
    db $30,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$30,$00,$00,$00 ;  59 '['
    db $00,$00,$40,$00,$40,$00,$00,$00,$20,$00,$20,$00,$10,$00,$10,$00 ;  60 '\'
    db $60,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$60,$00,$00,$00 ;  61 ']'
    db $00,$00,$60,$00,$50,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;  62 '^'
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;  63 '_'
    db $40,$00,$20,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;  64 '`'
    db $00,$00,$00,$00,$70,$00,$08,$00,$78,$00,$88,$00,$78,$00,$00,$00 ;  65 'a'
    db $80,$00,$80,$00,$E0,$00,$90,$00,$90,$00,$90,$00,$E0,$00,$00,$00 ;  66 'b'
    db $00,$00,$00,$00,$70,$00,$80,$00,$80,$00,$80,$00,$70,$00,$00,$00 ;  67 'c'
    db $08,$00,$08,$00,$78,$00,$88,$00,$88,$00,$88,$00,$78,$00,$00,$00 ;  68 'd'
    db $00,$00,$00,$00,$70,$00,$88,$00,$F8,$00,$80,$00,$70,$00,$00,$00 ;  69 'e'
    db $30,$00,$40,$00,$F0,$00,$40,$00,$40,$00,$40,$00,$40,$00,$00,$00 ;  70 'f'
    db $00,$00,$00,$00,$78,$00,$88,$00,$88,$00,$78,$00,$08,$00,$70,$00 ;  71 'g' (descender)
    db $80,$00,$80,$00,$E0,$00,$90,$00,$90,$00,$90,$00,$90,$00,$00,$00 ;  72 'h'
    db $40,$00,$00,$00,$C0,$00,$40,$00,$40,$00,$40,$00,$E0,$00,$00,$00 ;  73 'i'
    db $20,$00,$00,$00,$30,$00,$10,$00,$10,$00,$10,$00,$10,$00,$60,$00 ;  74 'j' (descender)
    db $80,$00,$80,$00,$90,$00,$A0,$00,$C0,$00,$A0,$00,$90,$00,$00,$00 ;  75 'k'
    db $40,$00,$40,$00,$40,$00,$40,$00,$40,$00,$40,$00,$60,$00,$00,$00 ;  76 'l'
    db $00,$00,$00,$00,$A8,$00,$A8,$00,$A8,$00,$A8,$00,$A8,$00,$00,$00 ;  77 'm'
    db $00,$00,$00,$00,$E0,$00,$90,$00,$90,$00,$90,$00,$90,$00,$00,$00 ;  78 'n'
    db $00,$00,$00,$00,$70,$00,$88,$00,$88,$00,$88,$00,$70,$00,$00,$00 ;  79 'o'
    db $00,$00,$00,$00,$E0,$00,$90,$00,$90,$00,$90,$00,$E0,$00,$80,$00 ;  80 'p' (descender)
    db $00,$00,$00,$00,$78,$00,$88,$00,$88,$00,$88,$00,$78,$00,$08,$00 ;  81 'q' (descender)
    db $00,$00,$00,$00,$B0,$00,$C0,$00,$80,$00,$80,$00,$80,$00,$00,$00 ;  82 'r'
    db $00,$00,$00,$00,$78,$00,$80,$00,$70,$00,$08,$00,$F0,$00,$00,$00 ;  83 's'
    db $40,$00,$E0,$00,$40,$00,$40,$00,$40,$00,$40,$00,$30,$00,$00,$00 ;  84 't'
    db $00,$00,$00,$00,$88,$00,$88,$00,$88,$00,$88,$00,$78,$00,$00,$00 ;  85 'u'
    db $00,$00,$00,$00,$88,$00,$88,$00,$88,$00,$50,$00,$20,$00,$00,$00 ;  86 'v'
    db $00,$00,$00,$00,$88,$00,$88,$00,$A8,$00,$A8,$00,$50,$00,$00,$00 ;  87 'w'
    db $00,$00,$00,$00,$88,$00,$50,$00,$20,$00,$50,$00,$88,$00,$00,$00 ;  88 'x'
    db $00,$00,$00,$00,$88,$00,$88,$00,$50,$00,$20,$00,$20,$00,$40,$00 ;  89 'y' (descender)
    db $00,$00,$00,$00,$F8,$00,$10,$00,$20,$00,$40,$00,$F8,$00,$00,$00 ;  90 'z'
FontTilesEnd:
