; Minimal text renderer: an 8x8 monospace font (ASCII $20 "space" through
; $5F "_" -- uppercase, digits, basic punctuation, tile index = ascii-$20)
; and a couple of primitives to load it and print null-terminated ROM
; strings into the BG tilemap. No word-wrap, no scrolling, no lowercase --
; exactly enough for short, fixed-position diagnostic status lines.
;
; The font bitmap data below is a straightforward 1-bit-per-pixel
; rasterization of a standard system monospace typeface at 8x8,
; thresholded to solid on/off pixels, generated by a local script for
; this project -- not a copied/embedded font file, and not derived from
; any Nintendo/Pokemon asset (see the repo-root CLAUDE.md's Copyright /
; Clean-Room Considerations section).

INCLUDE "hardware.inc"

SECTION "Text Code", ROM0

; Copies the 64-tile font into VRAM tile block 0 ($8000-$83FF). Must be
; called while the LCD is off (VRAM isn't safely writable with the LCD
; on outside HBlank/VBlank, and this copies more than fits in either
; window reliably) -- InitDisplayBlank in main.asm already does this
; before this is called.
; Clobbers: A, BC, HL, DE
LoadFont::
    ld hl, FontTiles
    ld de, $8000
    ld bc, FontTilesEnd - FontTiles
.loop
    ld a, [hl+]
    ld [de], a
    inc de
    dec bc
    ld a, b
    or a, c
    jr nz, .loop
    ret

; Prints a null-terminated ASCII string (chars $20-$5F only) into the BG
; tilemap starting at a given address. Turns the LCD off for the
; duration (simplest way to make this safe to call from anywhere,
; regardless of how long the string is or what PPU mode happens to be
; active at the time -- diagnostic code, not a hot path) and back on
; when done.
;
; Input:  HL = string pointer (ROM), DE = tilemap destination address
;         (e.g. $9800 + row*32 + col)
; Clobbers: A, HL, DE
PrintString::
    push af
    xor a, a
    ldh [rLCDC], a
    pop af
.loop
    ld a, [hl+]
    or a, a
    jr z, .done
    sub a, $20 ; ascii -> tile index
    ld [de], a
    inc de
    jr .loop
.done
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BG_TILEDATA
    ldh [rLCDC], a
    ret

; Fills the entire 32x32 BG tilemap with tile 0 (space, blank). Same
; LCD-off/on safety approach as PrintString.
;
; The zero-check runs *before* each write (see main.asm's FillMemory
; comment for why): an earlier version checked after writing and reused
; A for both "the value being written" and "BC==0 scratch", so only the
; very first tile actually got cleared and the rest of the screen kept
; whatever pattern was already in VRAM.
; Clobbers: A, BC, HL
ClearTextScreen::
    xor a, a
    ldh [rLCDC], a

    ld hl, $9800
    ld bc, 32 * 32
.loop
    ld a, b
    or a, c
    jr z, .cleared
    xor a, a
    ld [hl+], a
    dec bc
    jr .loop

.cleared
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BG_TILEDATA
    ldh [rLCDC], a
    ret

FontTiles:
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;   0 'space'
    db $00,$00,$20,$00,$20,$00,$20,$00,$20,$00,$00,$00,$20,$00,$00,$00 ;   1 '!'
    db $00,$00,$50,$00,$50,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;   2 '"'
    db $00,$00,$00,$00,$30,$00,$F8,$00,$50,$00,$F0,$00,$20,$00,$00,$00 ;   3 '#'
    db $00,$00,$20,$00,$70,$00,$60,$00,$70,$00,$30,$00,$70,$00,$20,$00 ;   4 '$'
    db $00,$00,$40,$00,$A0,$00,$70,$00,$70,$00,$28,$00,$10,$00,$00,$00 ;   5 '%'
    db $00,$00,$70,$00,$40,$00,$60,$00,$A8,$00,$90,$00,$78,$00,$00,$00 ;   6 '&'
    db $00,$00,$20,$00,$20,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;   7 '''
    db $20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;   8 '('
    db $40,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$40,$00,$00,$00 ;   9 ')'
    db $00,$00,$20,$00,$70,$00,$70,$00,$20,$00,$00,$00,$00,$00,$00,$00 ;  10 '*'
    db $00,$00,$00,$00,$20,$00,$20,$00,$F8,$00,$20,$00,$20,$00,$00,$00 ;  11 '+'
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$20,$00,$20,$00 ;  12 ','
    db $00,$00,$00,$00,$00,$00,$00,$00,$70,$00,$00,$00,$00,$00,$00,$00 ;  13 '-'
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$20,$00,$00,$00 ;  14 '.'
    db $00,$00,$10,$00,$10,$00,$20,$00,$20,$00,$00,$00,$40,$00,$40,$00 ;  15 '/'
    db $00,$00,$70,$00,$50,$00,$70,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  16 '0'
    db $00,$00,$60,$00,$20,$00,$20,$00,$20,$00,$20,$00,$70,$00,$00,$00 ;  17 '1'
    db $00,$00,$70,$00,$10,$00,$10,$00,$20,$00,$40,$00,$F0,$00,$00,$00 ;  18 '2'
    db $00,$00,$70,$00,$10,$00,$30,$00,$10,$00,$10,$00,$F0,$00,$00,$00 ;  19 '3'
    db $00,$00,$30,$00,$30,$00,$50,$00,$50,$00,$F0,$00,$10,$00,$00,$00 ;  20 '4'
    db $00,$00,$70,$00,$40,$00,$70,$00,$10,$00,$10,$00,$70,$00,$00,$00 ;  21 '5'
    db $00,$00,$70,$00,$40,$00,$70,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  22 '6'
    db $00,$00,$70,$00,$10,$00,$30,$00,$20,$00,$20,$00,$40,$00,$00,$00 ;  23 '7'
    db $00,$00,$70,$00,$50,$00,$70,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  24 '8'
    db $00,$00,$70,$00,$50,$00,$D0,$00,$70,$00,$10,$00,$60,$00,$00,$00 ;  25 '9'
    db $00,$00,$00,$00,$00,$00,$20,$00,$00,$00,$00,$00,$20,$00,$00,$00 ;  26 ':'
    db $00,$00,$00,$00,$00,$00,$20,$00,$00,$00,$00,$00,$20,$00,$20,$00 ;  27 ';'
    db $00,$00,$00,$00,$10,$00,$60,$00,$60,$00,$10,$00,$00,$00,$00,$00 ;  28 '<'
    db $00,$00,$00,$00,$00,$00,$F0,$00,$00,$00,$F0,$00,$00,$00,$00,$00 ;  29 '='
    db $00,$00,$00,$00,$C0,$00,$30,$00,$30,$00,$C0,$00,$00,$00,$00,$00 ;  30 '>'
    db $00,$00,$70,$00,$10,$00,$30,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;  31 '?'
    db $00,$00,$00,$00,$70,$00,$D0,$00,$B8,$00,$A8,$00,$B8,$00,$40,$00 ;  32 '@'
    db $00,$00,$20,$00,$70,$00,$50,$00,$50,$00,$70,$00,$98,$00,$00,$00 ;  33 'A'
    db $00,$00,$F0,$00,$D0,$00,$D0,$00,$F0,$00,$D0,$00,$F0,$00,$00,$00 ;  34 'B'
    db $00,$00,$30,$00,$40,$00,$40,$00,$40,$00,$40,$00,$30,$00,$00,$00 ;  35 'C'
    db $00,$00,$60,$00,$50,$00,$50,$00,$50,$00,$50,$00,$60,$00,$00,$00 ;  36 'D'
    db $00,$00,$70,$00,$40,$00,$40,$00,$70,$00,$40,$00,$70,$00,$00,$00 ;  37 'E'
    db $00,$00,$70,$00,$40,$00,$40,$00,$70,$00,$40,$00,$40,$00,$00,$00 ;  38 'F'
    db $00,$00,$70,$00,$40,$00,$40,$00,$50,$00,$50,$00,$70,$00,$00,$00 ;  39 'G'
    db $00,$00,$50,$00,$50,$00,$50,$00,$70,$00,$50,$00,$50,$00,$00,$00 ;  40 'H'
    db $00,$00,$70,$00,$20,$00,$20,$00,$20,$00,$20,$00,$70,$00,$00,$00 ;  41 'I'
    db $00,$00,$70,$00,$10,$00,$10,$00,$10,$00,$10,$00,$F0,$00,$00,$00 ;  42 'J'
    db $00,$00,$D0,$00,$F0,$00,$E0,$00,$E0,$00,$D0,$00,$D8,$00,$00,$00 ;  43 'K'
    db $00,$00,$40,$00,$40,$00,$40,$00,$40,$00,$40,$00,$78,$00,$00,$00 ;  44 'L'
    db $00,$00,$D0,$00,$D0,$00,$F0,$00,$B0,$00,$90,$00,$90,$00,$00,$00 ;  45 'M'
    db $00,$00,$D0,$00,$D0,$00,$F0,$00,$B0,$00,$90,$00,$90,$00,$00,$00 ;  46 'N'
    db $00,$00,$70,$00,$50,$00,$D0,$00,$D0,$00,$50,$00,$70,$00,$00,$00 ;  47 'O'
    db $00,$00,$70,$00,$50,$00,$50,$00,$70,$00,$40,$00,$40,$00,$00,$00 ;  48 'P'
    db $00,$00,$70,$00,$50,$00,$D0,$00,$D0,$00,$50,$00,$70,$00,$10,$00 ;  49 'Q'
    db $00,$00,$70,$00,$50,$00,$50,$00,$70,$00,$50,$00,$58,$00,$00,$00 ;  50 'R'
    db $00,$00,$70,$00,$40,$00,$60,$00,$30,$00,$10,$00,$70,$00,$00,$00 ;  51 'S'
    db $00,$00,$F0,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;  52 'T'
    db $00,$00,$D0,$00,$D0,$00,$D0,$00,$D0,$00,$50,$00,$70,$00,$00,$00 ;  53 'U'
    db $00,$00,$90,$00,$50,$00,$50,$00,$50,$00,$70,$00,$60,$00,$00,$00 ;  54 'V'
    db $00,$00,$88,$00,$88,$00,$A8,$00,$F0,$00,$50,$00,$50,$00,$00,$00 ;  55 'W'
    db $00,$00,$D0,$00,$70,$00,$20,$00,$20,$00,$50,$00,$D0,$00,$00,$00 ;  56 'X'
    db $00,$00,$D8,$00,$50,$00,$70,$00,$20,$00,$20,$00,$20,$00,$00,$00 ;  57 'Y'
    db $00,$00,$70,$00,$10,$00,$20,$00,$60,$00,$40,$00,$F8,$00,$00,$00 ;  58 'Z'
    db $30,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$30,$00,$00,$00 ;  59 '['
    db $00,$00,$40,$00,$40,$00,$00,$00,$20,$00,$20,$00,$10,$00,$10,$00 ;  60 '\'
    db $60,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$60,$00,$00,$00 ;  61 ']'
    db $00,$00,$60,$00,$50,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;  62 '^'
    db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ;  63 '_'
FontTilesEnd:
